version: "3.8"

services:
  omnitrix-backend:
    build:
      context: "."
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - omnitrix-db
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - DB_URL=jdbc:mysql://omnitrix-db:3306/omnitrix-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env

  omnitrix-db:
    image: mysql:8.0
    container_name: omnitrix-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123   # ✅ different root password
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env

volumes:
  db_data:
